/* QuickAid – ASWAN healthcare DEMO/PROJECT data (JSON-shaped).
   Collected 2026-10-03 from publicly listed directory pages found via web search (sources per record).
   NOT verified on Google Maps itself. Missing/unverifiable values are "Not available" or empty. May be outdated – verify before relying on it. */
const NA='Not available',LV='2026-10-03';
const S={
 auYP:'https://yellowpages.com.eg/en/profile/aswan-university-hospital/175796',
 auMed:'https://med.aswu.edu.eg/en/aswan-university-hospital/',
 auServ:'https://aswu.edu.eg/en/medical-services/aswan-university-hospitals',
 auWow:'https://wowinegypt.com/listing/aswan-university-hospitals/',
 hospCat:'https://yellowpages.com.eg/en/category/aswan-hospitals-&-medical-centers/26',
 hospP69:'https://yellowpages.com.eg/en/map-category/hospitals-&-medical-centers/p69',
 hospP18:'https://yellowpages.com.eg/en/map-category/hospitals-&-medical-centers/p18',
 met21:'https://www.metlife.eg/content/dam/metlifecom/eg/PDFs/medical-provider/English-Network-update-February-2021.pdf',
 met20:'https://www.metlife.eg/content/dam/metlifecom/eg/PDFs/medical-provider/English-Network-update-Feb-2020.pdf',
 phCat:'https://yellowpages.com.eg/en/category/aswan-pharmacies/26',
 phSS:'https://yellowpages.com.eg/en/map-search/24-hour-pharmacy/p216',
 medNile:'https://www.med.tn/pharmacy/aswan/nile-pharmacy--32046.html',
 medAswan:'https://www.med.tn/pharmacy-egypt/aswan',
 eyes:'https://yellowpages.com.eg/en/profile/aswan-eyes-&-laser-center/213071',
 dent:'https://www.medicawy.com/en/region/best-doctor-Dentistry/Aswan/Aswan/Egypt',
 pd:'https://eg.placedigger.com/category/clinic/location/aswan/'};
const ASWAN={
hospitals:[
{id:'h1',name:'Aswan University Hospital',description:'University hospital serving patients from Aswan Governorate and neighbouring governorates (per Aswan University Faculty of Medicine). The university page says its reception, emergency and orthopedic departments were still being developed.',address:'Kasr El Hagar St., El Sail Sharq, near the Traffic Station (plus code 3WP5+J4W)',area:'El Sail Sharq / Kasr El Hagar, Aswan',phone:'097 2428625',emergencyPhone:NA,specialties:['General Surgery','Surgical Oncology','Oral and Maxillofacial Surgery','Pediatric Surgery','Vascular Surgery','Neurosurgery','Plastic Surgery','Orthopedics','Urology and Nephrology','Ophthalmology','Oncology and Nuclear Medicine','Diagnostic Radiology','Dermatology and Venereology','Obstetrics','Cardiovascular Medicine','Cardio-Thoracic Surgery','Ear, Nose and Throat','Speech Therapy','Audiology','Internal Medicine','Neurology and Psychiatry','Tropical Medicine and Gastroenterology','Pediatrics','Rehabilitation and Physical Medicine','Clinical Pathology','Anesthesiology and Intensive Care','Chest Diseases'],services:['Medical convoys across Aswan Governorate and nearby cities'],workingHours:NA,rating:NA,image:'',mapQuery:'Aswan University Hospital, Kasr El Hagar, Aswan, Egypt',source:[S.auMed,S.auServ,S.auYP,S.auWow],lastVerified:LV,notes:'Another listing gives 097 2431022 (conflicting).'},
{id:'h2',name:'Aswan Teaching Hospital',description:NA,address:'Kasr El Hagar St., Downtown, Aswan',area:'Downtown / Kasr El Hagar, Aswan',phone:'097 2431022',emergencyPhone:NA,specialties:[],services:[],workingHours:NA,rating:NA,image:'',mapQuery:'Aswan Teaching Hospital, Kasr El Hagar, Aswan, Egypt',source:[S.met21,S.hospP18],lastVerified:LV,notes:'Phone from an insurance-network PDF (2021); may be outdated.'},
{id:'h3',name:'El Helal El Ahmar Specialized Hospital',description:NA,address:'Sharq El Bandar St., El Tabya Sq., beside El Tabya Mosque',area:'Downtown, Aswan',phone:NA,emergencyPhone:NA,specialties:[],services:[],workingHours:NA,rating:NA,image:'',mapQuery:'El Helal El Ahmar Specialized Hospital, Aswan, Egypt',source:[S.hospP69,S.hospCat],lastVerified:LV,notes:''},
{id:'h4',name:'Aswan Heart Center',description:'Listed inside Aswan Teaching Hospital.',address:'Kasr El Hagar St., inside Aswan Teaching Hospital',area:'Downtown, Aswan',phone:NA,emergencyPhone:NA,specialties:['Heart care (from facility name)'],services:[],workingHours:NA,rating:NA,image:'',mapQuery:'Aswan Heart Center, Kasr El Hagar, Aswan, Egypt',source:[S.hospP18],lastVerified:LV,notes:''},
{id:'h5',name:'Aswan Mental Health Hospital',description:NA,address:'El Sad El Aaly Sharq',area:'Downtown, Aswan',phone:NA,emergencyPhone:NA,specialties:['Mental health (from facility name)'],services:[],workingHours:NA,rating:NA,image:'',mapQuery:'Aswan Mental Health Hospital, Aswan, Egypt',source:[S.hospCat],lastVerified:LV,notes:''}],
pharmacies:[
{id:'p1',name:'Nile Pharmacy',address:'97 El Corniche St., beside Mobinil',area:'El Corniche, Aswan',phone:'+20 97 452 0257',workingHours:NA,rating:NA,availableMedicines:[],offers:[],image:'',mapQuery:'Nile Pharmacy, 97 El Corniche St, Aswan, Egypt',source:[S.medNile,S.phCat],lastVerified:LV},
{id:'p2',name:'Dr. Sayed Saber Pharmacy',address:'7 Salah El Din St., off Corniche El Nil',area:'Downtown, Aswan',phone:NA,workingHours:NA,rating:NA,availableMedicines:[],offers:[],image:'',mapQuery:'Dr Sayed Saber Pharmacy, Salah El Din St, Aswan, Egypt',source:[S.phSS,S.phCat,S.medAswan],lastVerified:LV},
{id:'p3',name:'El Wafaa Pharmacy',address:'Ahmed Maher St., beside Bata',area:'Downtown, Aswan',phone:'+20 97 227 0579',workingHours:NA,rating:NA,availableMedicines:[],offers:[],image:'',mapQuery:'El Wafaa Pharmacy, Ahmed Maher St, Aswan, Egypt',source:[S.medAswan,S.phCat],lastVerified:LV},
{id:'p4',name:'El Manara Pharmacy',address:'El Sheikh Haroun St., behind the Health Bureau – Aswan 1',area:'Downtown, Aswan',phone:'+20 97 473 3989',workingHours:NA,rating:NA,availableMedicines:[],offers:[],image:'',mapQuery:'El Manara Pharmacy, El Sheikh Haroun St, Aswan, Egypt',source:[S.medNile],lastVerified:LV},
{id:'p5',name:'Dr. Mohamed Omar Abdel Aziz Pharmacy',address:'Sharq El Bandar St., in front of National Societe Generale Bank',area:'Downtown, Aswan',phone:'+20 97 342 2460',workingHours:NA,rating:NA,availableMedicines:[],offers:[],image:'',mapQuery:'Dr Mohamed Omar Abdel Aziz Pharmacy, Sharq El Bandar St, Aswan, Egypt',source:[S.medAswan],lastVerified:LV},
{id:'p6',name:'Hedra Pharmacy',address:'Gameyet El Gabalawy St., near the Health Bureau',area:'El Sail Gharb, Aswan',phone:'+20 97 350 3000',workingHours:NA,rating:NA,availableMedicines:[],offers:[],image:'',mapQuery:'Hedra Pharmacy, Aswan, Egypt',source:[S.medAswan,S.phCat],lastVerified:LV,notes:'Yellow Pages lists the address as Kasr El Hagar St.; sources differ.'},
{id:'p7',name:'Abdin Pharmacies',address:'Corniche El Nil',area:'El Corniche, Aswan',phone:'097 2430543',workingHours:NA,rating:NA,availableMedicines:[],offers:[],image:'',mapQuery:'Abdin Pharmacies, Corniche El Nil, Aswan, Egypt',source:[S.phCat,S.met21],lastVerified:LV,notes:'Phone from an insurance-network PDF (2021); may be outdated.'},
{id:'p8',name:'El Gomhoureya Pharmacy',address:'El Emam El Shafaey St., off El Zalabeya Sq.',area:'Downtown, Aswan',phone:NA,workingHours:NA,rating:NA,availableMedicines:[],offers:[],image:'',mapQuery:'El Gomhoureya Pharmacy, Aswan, Egypt',source:[S.phCat],lastVerified:LV}],
clinics:[
{id:'c1',clinicName:'Aswan Eyes & Laser Center',doctorName:NA,specialty:'Eye care (from facility name)',address:'38 El Sadat Rd., in front of the Regional Center for Blood Transfusion',area:'Downtown, Aswan',phone:'097 2422988',bookingPhone:NA,workingHours:NA,rating:NA,image:'',mapQuery:'Aswan Eyes & Laser Center, El Sadat Rd, Aswan, Egypt',source:[S.eyes,S.hospP18],lastVerified:LV},
{id:'c2',clinicName:'Clinic of Dr. Ishaak Sobhy Shenouda',doctorName:'Dr. Ishaak Sobhy Shenouda',specialty:'Dermatology',address:'9 El-Shawarby St.',area:'Aswan',phone:'097 2304664',bookingPhone:NA,workingHours:NA,rating:NA,image:'',mapQuery:'Dr Ishaak Sobhy Shenouda, El Shawarby St, Aswan, Egypt',source:[S.met20],lastVerified:LV},
{id:'c3',clinicName:'Clinic of Dr. Kerolos Samir',doctorName:'Dr. Kerolos Samir',specialty:'Dental implants and orthodontics',address:'89 Corniche… (full address not available)',area:'Corniche, Aswan',phone:NA,bookingPhone:NA,workingHours:NA,rating:NA,image:'',mapQuery:'Dr Kerolos Samir dentist Corniche Aswan Egypt',source:[S.dent],lastVerified:LV},
{id:'c4',clinicName:'Clinic of Dr. Markos Saad',doctorName:'Dr. Markos Saad',specialty:'Dentistry and orthodontics',address:'3 Kasr el-Ha… (full address not available)',area:'Aswan',phone:NA,bookingPhone:NA,workingHours:NA,rating:NA,image:'',mapQuery:'Dr Markos Saad dentist Aswan Egypt',source:[S.dent],lastVerified:LV},
{id:'c5',clinicName:'Clinic of Dr. Hezem Khaled',doctorName:'Dr. Hezem Khaled',specialty:'Dentistry',address:'El Shawarby… (full address not available)',area:'Aswan',phone:NA,bookingPhone:NA,workingHours:NA,rating:NA,image:'',mapQuery:'Dr Hezem Khaled dentist Aswan Egypt',source:[S.dent],lastVerified:LV},
{id:'c6',clinicName:'مركز الأطباء (Doctors Center)',doctorName:NA,specialty:NA,address:'Aswan City Mall, 5th floor, beside El Tabya Mosque',area:'Aswan',phone:NA,bookingPhone:NA,workingHours:NA,rating:NA,image:'',mapQuery:'مركز الأطباء أسوان سيتي مول',source:[S.pd],lastVerified:LV}]};