/* QuickAid DEMO DATA (healthcare listings come from aswan-data.js) – in-memory "files": users, history, messages, ratings (reviews), medicines, offers, logs. Resets on reload. */
const ph=(t,c)=>'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="320"><rect width="100%" height="100%" fill="${c}"/><text x="50%" y="50%" fill="#fff" font-size="26" text-anchor="middle" font-family="sans-serif">${String(t).replace(/&/g,'and')}</text></svg>`);
const ok_=v=>v&&v!==NA,norm=(cat,r)=>{const name=r.name||r.clinicName;return{id:r.id,cat,name,area:[ok_(r.address)?r.address:'',r.area].filter(Boolean).join(', '),phones:[r.phone].filter(ok_),hours:r.workingHours||NA,rating:r.rating||NA,mapQuery:r.mapQuery,source:r.source,lastVerified:r.lastVerified,description:r.description||'',reviews:[],announcements:[],img:ok_(r.image)?r.image:ph(name,'#0d6efd')}};
const HOSP=ASWAN.hospitals.map(r=>{const e=norm('hospital',r);return{...e,emergency:r.emergencyPhone||NA,specialties:r.specialties,services:r.services,images:[e.img]}});
const PHAR=ASWAN.pharmacies.map(r=>({...norm('pharmacy',r),medicines:(r.availableMedicines||[]).map((m,j)=>({id:r.id+'_m'+j,name:m.name,price:m.price,avail:m.available})),offers:r.offers||[]}));
const CLIN=ASWAN.clinics.map(r=>({...norm('clinic',r),doctor:r.doctorName,specialty:r.specialty,booking:[r.bookingPhone].filter(ok_),services:r.services||[]}));
const DB={
users:[
{id:1,type:'customer',email:'customer@quickaid.com',password:'123456',name:'Reem Ashraf',phone:'01000000001',follows:[]},
{id:2,type:'pharmacy',email:'pharmacy@quickaid.com',password:'123456',name:'Nile Pharmacy',entityId:'p1'},
{id:3,type:'hospital',email:'hospital@quickaid.com',password:'123456',name:'Aswan University Hospital',entityId:'h1'},
{id:4,type:'clinic',email:'clinic@quickaid.com',password:'123456',name:'Aswan Eyes & Laser Center',entityId:'c1'}],
hospitals:HOSP,pharmacies:PHAR,clinics:CLIN,
history:[],logs:[],
messages:[{cid:1,eid:'p1',from:'b',text:'Welcome to Nile Pharmacy (demo message, not from the real pharmacy).',t:'Demo'}],
stats:[{n:'Road accidents',v:80,i:'bi-car-front-fill'},{n:'Burns',v:62,i:'bi-fire'},{n:'Falls',v:70,i:'bi-arrow-down-circle'},{n:'Drowning',v:35,i:'bi-water'},{n:'Poisoning',v:45,i:'bi-capsule'},{n:'Choking',v:28,i:'bi-exclamation-octagon'}]};
const A_=(n,s,d,e)=>({n,s:s.split('|'),d:d.split('|'),e:e.split('|')});
const AID=[
A_('Burns','Move away from the heat source|Cool the burn under cool running water for 20 minutes|Remove rings/clothing near the burn unless stuck|Cover loosely with cling film or a clean non-fluffy dressing','Use ice, butter or toothpaste|Burst blisters|Pull off stuck clothing','Large, deep, face/hand/genital, chemical or electrical burns, or any burn in a child or with breathing trouble'),
A_('Cuts and Bleeding','Wash hands or wear gloves|Press firmly on the wound with a clean cloth|Raise the injured limb|Add more cloth if soaked; then bandage','Remove embedded objects|Remove soaked cloth|Use a tourniquet unless trained','Bleeding that does not stop after 10 minutes, spurting blood, deep wounds, embedded objects or signs of shock'),
A_('Choking','Encourage the person to keep coughing|If they cannot cough or speak: give up to 5 back blows|Then up to 5 abdominal thrusts (infants: back blows and chest thrusts)|Alternate until clear','Do blind finger sweeps|Hit the back if they can cough effectively','Call for help if the blockage does not clear, if the person becomes unresponsive (start CPR), or after any abdominal thrusts'),
A_('Fractures','Keep the person still and support the injury|Control any bleeding|Apply a wrapped cold pack|Immobilise the limb as found','Straighten the limb|Give food or drink|Move the person unless in danger','Suspected head, neck or back injury, open fracture, or a numb, pale or blue limb'),
A_('Fainting','Lay the person flat|Raise their legs about 30 cm|Loosen tight clothing and ensure fresh air|Help them sit up slowly once recovered','Sit them up quickly|Give food or drink while unconscious','Unconscious for more than a minute, injury, chest pain, pregnancy or abnormal breathing'),
A_('Nosebleed','Sit up and lean forward|Pinch the soft part of the nose for 10–15 minutes|Breathe through the mouth|Apply a cold compress','Lean back|Pack the nose deeply|Blow the nose afterwards','Bleeding over 20 minutes, after a head injury, heavy bleeding or if on blood thinners'),
A_('Sprains','Rest the joint|Ice wrapped in cloth for 20 minutes|Compress with a bandage|Elevate above heart level','Apply heat in the first 48 hours|Massage the area|Keep walking on it','Cannot bear weight, deformity, numbness or severe swelling'),
A_('Heatstroke','Move to a cool, shaded place|Call emergency services|Remove excess clothing and cool the skin with water and a fan|Sip water only if fully alert','Give fluids if confused or unconscious|Give fever medicine','Immediately: confusion, hot dry or sweaty skin, collapse or seizure'),
A_('Poisoning','Call emergency services or a poison centre|Identify the substance and keep the container|Skin: remove contaminated clothing and rinse|Eyes: rinse with water for 15 minutes','Induce vomiting|Give food, drink or antidotes unless advised','Always get professional advice immediately'),
A_('Electric Shock','Do not touch the person until power is off|Switch off at the source, or move the source with a dry non-conductive object|Check breathing; start CPR if needed|Cool any burns','Touch while still in contact|Use wet or metal objects','Always – electric shock can cause hidden heart problems'),
A_('Drowning','Shout for help and call emergency services|Reach or throw an aid; do not enter deep water|If not breathing, give 5 rescue breaths then CPR|Place in recovery position once breathing; keep warm','Attempt a swim rescue without training|Press on the stomach to remove water','Always'),
A_('Heart Attack','Call 123 immediately|Sit the person in a comfortable position|If advised and not allergic, chew one adult aspirin|Be ready to start CPR if they stop responding','Let them walk or drive themselves|Give food or drink','Immediately – any chest pain lasting more than a few minutes')];
const BOT=[['How do I treat a burn?','Cool under cool running water for 20 minutes and cover loosely. No ice or creams. See the First Aid page.'],['What if someone is choking?','If they cannot cough or speak: 5 back blows, then 5 abdominal thrusts, and call for help.'],['How do I stop bleeding?','Press firmly with a clean cloth and raise the limb. Call for help if it does not stop in 10 minutes.'],['Emergency numbers in Egypt?','Ambulance 123, Police 122, Fire 180.'],['How do I find hospitals?','Open Hospitals or use the search bar with the Hospitals filter.'],['How do I find pharmacies?','Open Pharmacies or search a medicine name with the Pharmacies filter.']];
